config/routes.rb
Rails.application.routes.draw do
  root 'billboards#index'

  resources :billboards do
    resources :artists
  end

  resources :artists do
    resources :songs
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates_presence_of :name, :album

  belongs_to :billboard
  has_many :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  validates_presence_of :name

  has_many :artists
  has_many :songs

end

app/models/song.rb
class Song < ApplicationRecord
  validates_presence_of :title, :album

  belongs_to :artist
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_billboard
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = @billboard.artists
  end

  def show
  end

  def new
    @artist = Artist.new 
  end

  def create
    @artist = @billboard.artists.new(artist_params)
    if @artist.save
      redirect_to billboard_artist_path(@billboard, @artist)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to billboard_artist_path(@billboard, @artist)
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to billboard_artists_path(@billboard)
  end

  private
    def artist_params
      params.require(:artist).permit(:name, :album, :billboard_id)
    end

    def set_billboard
      @billboard = Billboard.find(params[:billboard_id])
    end

    def set_artist
      @artist = @billboard.artists.find(params[:id])
    end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :update, :destroy]

  def index
    @billboards = Billboard.all
  end

  def show
    @artists = @billboard.artists.all
  end

  def new
    @billboard = Billboard.new 
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboard_path(@billboard)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to billboard_path(@billboard)
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  private
    def billboard_params
      params.require(:billboard).permit(:name)
    end

    def set_billboard
      @billboard = Billboard.find(params[:id])
    end
    
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @artist.songs
  end

  def show
  end

  def new
    @song = Song.new 
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to artist_song_path(@artist, @song)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to artist_song_path(@artist, @song)
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to artist_songs_path(@artist)
  end

  private
    def song_params
      params.require(:song).permit(:title, :album, :artist_id)
    end

    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def set_song
      @song = @artist.songs.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for [@billboard, @artist] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :album %>
  <%= f.text_field :album %>
  <br />

  <%= f.submit %>

<% end %>

app/views/artists/edit.html.erb
<%= render(partial: 'form') %>

<%= link_to 'Back', artist_path(@artist) %>

app/views/artists/index.html.erb
<h1>Billboard Artists</h1>

<% @artists.each do |artist| %>
    <h3><%= artist.name %></h3>
    <h4><%= artist.album %></h4>
    <%= link_to 'Show', billboard_artist_path(@billboard, artist) %>
    <%= link_to 'Songs', artist_songs_path(artist) %>
<% end %>

<%= link_to 'New Artist', new_billboard_artist_path(@billboard) %>

app/views/artists/new.html.erb
<%= render(partial: 'form') %>

<%= link_to 'Back', billboard_path(@billboard) %>

app/views/artists/show.html.erb
<h1> <%= @artist.name %> </h1>

<ul>
  <li>Name: <%= @artist.name %> </li>
  <li>
    <%= link_to 'Edit', edit_billboard_artist_path(@billboard, @artist) %>
    <%= link_to 'Delete', billboard_artist_path(@billboard), method: :delete, data: {confirm: 'Really Delete?'} %>
  </li>
</ul>

<ul>
  <li>Name: <%= @artist.album %> </li>
  <li>
    <%= link_to 'Edit', edit_billboard_artist_path(@billboard, @artist) %>
    <%= link_to 'Delete', billboard_artist_path(@billboard), method: :delete, data: {confirm: 'Really Delete?'} %>
  </li>
</ul>

<%= link_to 'Home', billboard_artists_path(@billboard) %>

app/views/billboards/_form.html.erb
<%= form_for @billboard do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.submit %>

<% end %>

app/views/billboards/edit.html.erb
<h1>Edit this Entry</h1>

<%= render(partial: 'form') %>

<%= link_to 'Back', billboards_path %>

app/views/billboards/index.html.erb
<h1 class='center background'>Billboard Charts</h1>

<div class='row'>
<% @billboards.each do |billboard| %>
    <h3><%= billboard.name %></h3>
        <div class'col s12 m3'>
    <%= link_to 'Show', billboard_path(billboard) %>
    <%= link_to 'Artists', billboard_artists_path(billboard) %>
<% end %>
    </div>
</div>

<%= link_to 'New Billboard', new_billboard_path %>

app/views/billboards/new.html.erb
<h1>Add New Billboard Charts</h1>

<%= render(partial: 'form') %>

<%= link_to 'Back', billboards_path %>

app/views/billboards/show.html.erb
<h1 class="center"> <%= @billboard.name %> </h1>

<ul>
  <li>Name: <%= @billboard.name %> </li>
  <li>
    <%= link_to 'Edit', edit_billboard_path(@billboard) %>
    <%= link_to 'Delete', billboard_path(@billboard), method: :delete, data: {confirm: 'Really Delete?'} %>
  </li>
</ul>

<%= link_to 'Back', billboards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBillboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for [@artist, @song] do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />

  <%= f.label :album %>
  <%= f.text_field :album %>
  <br />

  <%= f.submit %>

<% end %>

app/views/songs/edit.html.erb
<%= render(partial: 'form') %>

<%= link_to 'Back', artist_song_path(@artist, @song) %>

app/views/songs/index.html.erb
<h1>Artist's Songs</h1>

<% @songs.each do |song| %>
    <h3><%= song.title %></h3>
    <h4><%= song.album %></h4>
    <%= link_to 'Show', artist_song_path(@artist, song) %>
<% end %>

<%= link_to 'New Song', new_artist_song_path(@artist) %>
<%= link_to 'Home', billboards_path %>

app/views/songs/new.html.erb
<%= render(partial: 'form') %>

<%= link_to 'Back', artist_songs_path(@artist) %>

app/views/songs/show.html.erb
<h1> <%= @song.title %> </h1>

<ul>
  <li>Name: <%= @song.title %> </li>
  <li>
    <%= link_to 'Edit', edit_artist_song_path(@artist, @song) %>
    <%= link_to 'Delete', artist_song_path(@artist), method: :delete, data: {confirm: 'Really Delete?'} %>
  </li>
</ul>

<ul>
  <li>Name: <%= @song.album %> </li>
  <li>
    <%= link_to 'Edit', edit_artist_song_path(@artist, @song) %>
    <%= link_to 'Delete', artist_song_path(@artist), method: :delete, data: {confirm: 'Really Delete?'} %>
  </li>
</ul>

<%= link_to 'Home', artist_songs_path(@artist) %>